[environment]
NAME = "John"

[[includes]]
url = "https://github.com/philipdexter/std.mold"

[types.python]
command = ["python", "?"]
extensions = ["py"]

[recipes.this]
url = "https://github.com/scizzorz/mold.git"
help = "Recursive remote include"
environment = {NAME = "Group"}

[recipes.shell]
help = "Test sh script"
type = "sh"

[recipes.subshell]
environment = {NAME = "Test"}
help = "Test sh script"
type = "sh"
script = "shell.sh"

[recipes.python]
help = "Test Python script"
type = "python"

[recipes.nop]
help = "Test no-op"

[recipes.fmt]
help = "Format using rustfmt"
command = ["cargo", "fmt"]

[recipes.build]
help = "Build using cargo"
command = ["cargo", "build"]

[recipes.clean]
help = "Clean build artifacts using cargo"
command = ["cargo", "clean"]

[recipes.lint]
help = "Lint using clippy"
command = ["cargo", "clippy", "--", "-D", "warnings"]
deps = ["clean"]
