[environment]
NAME = "John"

[[includes]]
url = "https://github.com/philipdexter/std.mold"

[[includes]]
url = "https://github.com/scizzorz/cargo.mold"

[types.python]
command = ["python", "?"]
extensions = ["py"]

[recipes.this]
url = "https://github.com/scizzorz/mold.git"
help = "Recursive remote include"
environment = {NAME = "Group"}

[recipes.shell]
help = "Test sh script"
type = "sh"

[recipes.subshell]
environment = {NAME = "Test"}
help = "Test sh script"
type = "sh"
script = "shell.sh"

[recipes.python]
help = "Test Python script"
type = "python"

[recipes.nop]
help = "Test no-op"
